### ISSUE TITLE
Error when studying

### ISSUE THREAD

**Issue by cjdduarte** [XavierScherschligt/RuneScape-Gamification#1] opened 2022-12-22 08:51 UTC
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-12-22 05:44:33

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 562, in handler
  File "aqt.reviewer", line 655, in _onTypedAnswer
  File "aqt.reviewer", line 417, in _showAnswer
  File "_aqt.hooks", line 3761, in __call__
  File "anki.hooks", line 34, in runHook
  File "C:\Users\cjddu\AppData\Roaming\Anki2\addons21\931346754\__init__.py", line 176, in on_show_answer
    increase_skill_progress("speed", speed_xp)
  File "C:\Users\cjddu\AppData\Roaming\Anki2\addons21\931346754\__init__.py", line 141, in increase_skill_progress
    level_up(skill_label, skill)
  File "C:\Users\cjddu\AppData\Roaming\Anki2\addons21\931346754\__init__.py", line 93, in level_up
    anim.setEasingCurve(QEasingCurve.OutBounce)
AttributeError: type object 'QEasingCurve' has no attribute 'OutBounce'

**Comment by XavierScherschligt** [comment] 2022-12-22 19:29
This error was caused by code I was working on to better animate level ups but I have moved away from the idea for now, should be fixed (by omission) with Version 1.0.2, let me know if not, otherwise I'll close this issue.

Best,
-XS

**Closed** 2022-12-23 04:39 UTC
